# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 619c47a3e55f1ba8d866e10991e1ac2d6d4cf1a230891d36751423960022c12e11817247552b836d70586f40de49b35d2cbf242c8cf9082b4b8c3d295628fab5

test:
  secret_key_base: 0eb33476d317f292e996ca830803e1aef6368955e2800843116e6fad8d257f615ec14d7b235812f1b92f37c0ddb653aec335a1f55275c55625b8da676f978d08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
